ENV["LC_ALL"] = "zh_TW.UTF-8"
Vagrant.require_version ">= 2.2.19"
Vagrant.configure(2) do |config|
   config.vm.box = "generic/debian10"
   config.vm.box_version = "4.0.2"
   config.vm.define vm_name = 'terraform.docker.lab'
  
   config.vm.provision "docker" do |docker|
     docker.pull_images "hashicorp/terraform:1.2.4"
   end

   config.vm.provision "shell", privileged: false, inline: <<-SHELL
     sudo apt-get update
     
     # step1: instal neovim
     sudo curl -Lo /var/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
     sudo tar -C /etc/ -zxvf /var/nvim-linux64.tar.gz
     echo 'export PATH=$PATH:/etc/nvim-linux64/bin' >> ~/.bash_profile

     # step2: install tfenv tool
     git clone https://github.com/tfutils/tfenv.git ~/.tfenv
     echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
     sudo ln -s ~/.tfenv/bin/* /usr/local/bin
   SHELL

   config.vm.network :private_network, ip: "172.168.10.10"
   config.vm.provision "file", source: "../src", destination: "/home/vagrant/src"
   config.vm.provider "hyperv" do |h|
     h.cpus = 4
     h.memory = 2048
   end
end
